name: Deploy Dagster App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Install required system packages
          sudo apt-get update
          sudo apt-get install -y python3-venv python3-pip git

          # Create app directory if it doesn't exist
          mkdir -p ~/airbnb-analytics
          
          # Clone/pull repository
          if [ -d "~/airbnb-analytics/.git" ]; then
            cd ~/airbnb-analytics
            git pull origin main
          else
            rm -rf ~/airbnb-analytics
            git clone ${{ github.server_url }}/${{ github.repository }} ~/airbnb-analytics
            cd ~/airbnb-analytics
          fi
          
          # Setup Python virtual environment
          python3 -m venv venv
          source venv/bin/activate
          
          # Upgrade pip and install dependencies
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt
          
          # Create data directory if it doesn't exist
          mkdir -p data
          
          # Create persistent Dagster home directory
          mkdir -p ~/dagster_home
          
          # Create systemd service file
          sudo tee /etc/systemd/system/dagster.service << EOF
          [Unit]
          Description=Dagster Server
          After=network.target

          [Service]
          Type=simple
          User=ubuntu
          WorkingDirectory=/home/ubuntu/airbnb-analytics
          Environment="PATH=/home/ubuntu/airbnb-analytics/venv/bin"
          Environment="PYTHONPATH=/home/ubuntu/airbnb-analytics"
          Environment="DAGSTER_HOME=/home/ubuntu/dagster_home"
          ExecStart=/home/ubuntu/airbnb-analytics/venv/bin/dagster dev -f sales_pipeline/assets.py --host 0.0.0.0 --port 3000
          Restart=always
          RestartSec=1

          [Install]
          WantedBy=multi-user.target
          EOF
          
          # Reload systemd and restart service
          sudo systemctl daemon-reload
          sudo systemctl enable dagster
          sudo systemctl restart dagster
          
          # Wait for service to start and check status
          sleep 5
          sudo systemctl status dagster
          
          # Verify port is listening
          netstat -tulpn | grep 3000 